2019-12-05 18:15 -> Update

diff --git a/bash/appendChangelog b/bash/appendChangelog
--- a/bash/appendChangelog
+++ b/bash/appendChangelog
@@ -1,8 +1,21 @@
 # !/bin/bash
 #
-#	Appende al file $path la stringa di data creata con il formato di printDate, e lo apre con subl (SublimeTextEditor)
+#	Appende al file $path la stringa di data creata con il formato di printDate, e lo apre con subl
 #
-#	Richiede printDate, subl
+#	Richiede printDate (bash personalizzato), subl (SublimeTextEditor)
 #
+
 path="/home/giuseppe/Linux/changelog"
-printDate >> $path && subl $path
+
+#if per controllare la presenza dei comandi
+if [ $(command -v subl) -a $(command -v printDate) -a -w $path ] ;
+then
+	echo "Appending to $path"
+	printDate >> $path && subl $path
+	exit 0
+else
+	echo -e "Missing: printDate, subl.\nExiting now."
+	exit 1
+fi
+
+
